---
- name: Load ssh_host_key into a variable (used in postinstall.sh)
  set_fact:
    ssh_host_ed25519_key: "{{ lookup('ansible.builtin.file', inventory_hostname + '/ssh_host_ed25519_key') }}"

- name: Load ssh_host_key.pub into a variable (used in postinstall.sh)
  set_fact:
    ssh_host_ed25519_key_pub: "{{ lookup('ansible.builtin.file', inventory_hostname + '/ssh_host_ed25519_key.pub') }}"

- name: Copy Install Script for Hetzner's Debian version
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  template:
    src: install_image.conf.j2
    dest: /tmp/install_image.conf
    mode: 0755

- name: Copy post-install script (mainly dropbear and ssh setup)
  when: ansible_os_family == "Debian"
  tags: hetznerinit
  template:
    src: postinstall_setup.sh.j2
    dest: /tmp/postinstall_setup.sh
    mode: 0755

- name: Wipe old root.
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  command: "dd bs=1M if=/dev/urandom of=/dev/sda"
  ignore_errors: yes  # dd always fails with out of space

- name: Execute Install Image
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  shell: '/root/.oldroot/nfs/install/installimage -a -c /tmp/install_image.conf -x /tmp/postinstall_setup.sh'

- name: reboot
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  reboot:
