---
- name: Mount current OS - virtual volumes (chmod)
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  mount:
    path: "/mnt/{{ item }}"
    src: "/{{ item }}"
    opts: bind
    fstype: none
    state: mounted
  loop:
    - dev
    - sys
    - proc
  loop_control:
    label: "{{ item }}"
