---
- name: Mount crypted root volume
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  mount:
    path: /mnt
    src: /dev/mapper/root
    fstype: ext4
    state: mounted

- name: Create /mnt/boot on crypted root
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  file:
    path: /mnt/boot
    state: directory
    mode: '0755'

- name: Mount boot volume
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  mount:
    path: /mnt/boot
    src: /dev/sda1
    fstype: ext4
    state: mounted
