---
- name: Mount current OS - root volume
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  mount:
    path: /mnt
    src: /dev/sda2
    fstype: ext4
    state: mounted

- name: Mount current OS - boot volume (chmod)
  when: ansible_os_family == 'Debian'
  tags: hetznerinit
  mount:
    path: /mnt/boot
    src: /dev/sda1
    fstype: ext4
    state: mounted
