---
- name: Unmount current OS - virtual volumes (chmod)
  when: ansible_os_family == 'Debian'
  tags: hetznerinit 
  mount:
    path: "/mnt/{{ item }}"
    opts: bind
    state: unmounted
  loop:
    - dev
    - sys
    - proc
    - boot
    - "/"
  loop_control:
    label: "{{ item }}"
